### PR TITLE
fix manual constraint store and deletion and rejig UI to make a littl…

### PR DESCRIPTION
**Pull request by RichLinnell**
…e more intuitive for us newbies.

### CODE REVIEW

**Comment by zcanann** [comment]
I like the idea of just putting a remove and edit button inline with the constraint itself -- I've been talking to some other users also having issues with manual scanning being counter-intuitive.

There are some larger UI/UX issues that need to be resolved, which will require a larger refactor. 95+% of the time most people just scan for one constraint. I want to optimize for this case and keep the number of clicks required to a minimum. So I don't want to force people to add to the list and clear it all of the time, but I also want it to be obvious that it isn't necessary.

I'm putting in a PR that works off of some of the ideas you had going on, (https://github.com/Anathena/Anathena/pull/168) with some other larger refactors

I've been doing this for 10 years so unfortunately I'm a bit accustomed to memory editors, so if some of the UI/UX still seems horrible, I'm always open to suggestions

**Comment by zcanann** [comment]
Also I'm gonna set up the branches to be more friendly to other developers, I guess you get to be the canary in the coal mine

**Comment by RichLinnell** [comment]
No pprobs.  This is my first forage into open source contributions, so we can both learn ;).  Have you thought of using Caliburn Micro?  it would make all the Mvvm stuff so much simpler, and you get an Event Aggregator, so firing things off onto Async tasks and then raising events on them and listening for these events on the UI thread is a breeze.

Just some suggestions from my own WPF experiences in the commercial dev world.

**Comment by zcanann** [comment]
DI would probably be useful, I'm abusing singletons a bit too hard.

Haven't done a ton of research into MVVM frameworks or DI stuff yet, but its somewhere on the never-ending TODO list.

**Pull request closed without merging**
